; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare-s3-eth]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino

board_build.filesystem = littlefs
monitor_speed = 115200

; ---- FORCE correct hardware ----
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
 
board_build.partitions = default_16MB.csv

; IMPORTANT: enforce PSRAM at compile level
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_SPIRAM=1
  -DCONFIG_SPIRAM_MODE_OCT=1
  -DCONFIG_SPIRAM_TYPE_AUTO=1
  -DCONFIG_ESP_WIFI_ENABLED=1
  -Isrc/

lib_deps = 
	adafruit/Adafruit BusIO@^1.15.0
	adafruit/Adafruit Unified Sensor@^1.1.14
	fbiego/ESP32Time@^2.0.4
	plageoj/UrlEncode@^1.0.1
	bblanchon/ArduinoJson@^7.0.3
	fatlab101/FixedString@^0.1.1
	wifwaf/MH-Z19@^1.5.4
	ESP32Async/AsyncTCP@3.4.10
	locoduino/RingBuffer@^1.0.5
	jcomas/S8_UART@^1.0.1
	robtillaart/SHT31@^0.5.3
	paulstoffregen/Time@^1.6.1
	khoih-prog/Timezone_Generic@^1.10.1
	mikalhart/TinyGPSPlus@^1.0.3
	janelia-arduino/Vector@^1.2.2
	https://github.com/ESP32Async/ESPAsyncWebServer
	Wire
	SPI
	adafruit/Adafruit SHT4x Library@^1.0.4
	WiFi

lib_ignore = 
	WiFi101
	WiFi101_Generic
	WiFiEspAT
	WiFiNINA_Generic
	ESP8266_AT_WebServer
    EthernetENC
	UIPEthernet
	WiFiWebServer
	WiFiWebServer_RTL8720
	EthernetWebServer_STM32